"""empty message

Revision ID: 38aff3fe1430
Revises: 4c2b2ac1d532
Create Date: 2019-11-02 19:46:26.006945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aff3fe1430'
down_revision = '4c2b2ac1d532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('middle_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('warehouse_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('units_of_measure', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('warehouse_actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_actor_id'], ['warehouse_actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_warehouse_name'), 'warehouse', ['warehouse_name'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'warehouse_id')
    )
    op.drop_table('warehouse_products')
    op.drop_table('warehouse_actors')
    op.drop_index('ix_warehouses_warehouse_name', table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('warehouse_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('warehouse_actor_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='warehouses_pkey')
    )
    op.create_index('ix_warehouses_warehouse_name', 'warehouses', ['warehouse_name'], unique=False)
    op.create_table('warehouse_actors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='warehouse_actors_pkey')
    )
    op.create_table('warehouse_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('units_of_measure', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='warehouse_products_pkey')
    )
    op.drop_table('products')
    op.drop_index(op.f('ix_warehouse_warehouse_name'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_table('warehouse_product')
    op.drop_table('warehouse_actor')
    # ### end Alembic commands ###
